fail_fast: false
exclude: ^.*\b(migrations)\b.*$
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.10
      hooks:
          - id: ruff-check
            args: [--fix]
          - id: ruff-format
