services:
    fastapi:
        container_name: work_match_api
        build: ..
        environment:
            - PYTHONPATH=./src
        ports:
            - ${API_PORT}:8000
            - ${DEBUG_PORT}:5678
        command: >
            sh -c "debugpy --listen 0.0.0.0:5678 -m uvicorn --factory src.core.server:create_app --reload --host 0.0.0.0 --port 8000 & celery -A worker.worker worker -l info"
        volumes:
            - ..:/work_match_api
        networks:
            - work_match_api
        healthcheck:
            test:
                [
                    "CMD",
                    "curl",
                    "-f",
                    "http://localhost:8000/v1/monitoring/health/",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
        restart: unless-stopped
        depends_on:
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
            postgres:
                condition: service_healthy
            elasticsearch:
                condition: service_healthy
networks:
    work_match_api:
        driver: bridge
