services:
    fastapi:
        container_name: work_match_api
        build: ..
        environment:
            - PYTHONPATH=./src
        ports:
            - ${API_PORT}:8000
        command: >
            poetry run python src/main.py
        volumes:
            - ..:/work_match_api
        networks:
            - work_match_api

networks:
    work_match_api:
        driver: bridge
