services:
    fastapi:
        container_name: work_match_api
        build: ..
        environment:
            - PYTHONPATH=./src
        ports:
            - ${API_PORT}:8000
            - 5678:5678
        command: >
            sh -c "debugpy --listen 0.0.0.0:5678 -m uvicorn --factory src.core.server:create_app --reload --host 0.0.0.0 --port 8000 & celery -A worker.worker worker -l info"
        volumes:
            - ..:/work_match_api
        networks:
            - work_match_api

networks:
    work_match_api:
        driver: bridge
