services:
    postgres:
        image: postgres
        container_name: work_match_api_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - work_match_api_postgres:/var/lib/postgresql/data
        networks:
            - work_match_api

    redis:
        image: redis
        container_name: work_match_api_redis
        ports:
            - 6379:6379
        volumes:
            - work_match_api_redis:/data
        networks:
            - work_match_api
        restart: unless-stopped

volumes:
    work_match_api_postgres:
    work_match_api_redis:

networks:
    work_match_api:
        driver: bridge
