services:
    postgres:
        image: postgres
        container_name: work_match_api_postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - work_match_api_postgres:/var/lib/postgresql/data
        networks:
            - work_match_api
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s
        restart: unless-stopped

    redis:
        image: redis
        container_name: work_match_api_redis
        ports:
            - 6379:6379
        volumes:
            - work_match_api_redis:/data
        networks:
            - work_match_api
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s
        restart: unless-stopped

    elasticsearch:
        image: elasticsearch:8.16.6
        container_name: work_match_api_elasticsearch
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - xpack.security.enabled=false
        ports:
            - 9200:9200
        volumes:
            - work_match_api_elastic:/usr/share/elasticsearch/data
        networks:
            - work_match_api
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -fsSL http://localhost:9200/_cluster/health || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s
        restart: unless-stopped

    kibana:
        image: kibana:8.16.6
        container_name: work_match_api_kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        networks:
            - work_match_api
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "curl -fsSL http://localhost:5601/api/status || exit 1",
                ]
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 30s
        restart: unless-stopped

volumes:
    work_match_api_postgres:
    work_match_api_redis:
    work_match_api_elastic:

networks:
    work_match_api:
        driver: bridge
