"""Specialist Skill refactor

Revision ID: 1159d47e376d
Revises: a4a8e1adf830
Create Date: 2025-03-09 14:37:39.577056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1159d47e376d"
down_revision: Union[str, None] = "a4a8e1adf830"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specialist_skills", sa.Column("skill_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specialist_skills", "skill_name")
    # ### end Alembic commands ###
