"""Fixed roles

Revision ID: 81c1e3cf0013
Revises: 12675a4e54f2
Create Date: 2025-03-01 11:40:33.355785

"""

from typing import (
    Sequence,
    Union,
)

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "81c1e3cf0013"
down_revision: Union[str, None] = "12675a4e54f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_admin", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
