"""empty message

Revision ID: 98b82f490681
Revises: 3d5dfbed1a9a
Create Date: 2025-03-24 20:04:45.096320

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '98b82f490681'
down_revision: Union[str, None] = '3d5dfbed1a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_specialist_vacancy', 'applications', ['specialist_uuid', 'vacancy_uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_specialist_vacancy', 'applications', type_='unique')
    # ### end Alembic commands ###
