"""EmploymentType

Revision ID: b4454969cd5a
Revises: 1159d47e376d
Create Date: 2025-03-09 14:40:25.018349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4454969cd5a"
down_revision: Union[str, None] = "1159d47e376d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specialists", sa.Column("employment_type_id", sa.BigInteger(), nullable=True)
    )
    op.create_foreign_key(
        None, "specialists", "employment_types", ["employment_type_id"], ["o_id"]
    )
    op.drop_constraint("users_employment_type_id_fkey", "users", type_="foreignkey")
    op.drop_column("users", "employment_type_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "employment_type_id", sa.BIGINT(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "users_employment_type_id_fkey",
        "users",
        "employment_types",
        ["employment_type_id"],
        ["o_id"],
    )
    op.drop_constraint(None, "specialists", type_="foreignkey")
    op.drop_column("specialists", "employment_type_id")
    # ### end Alembic commands ###
