"""uuid's and salary for vacancy

Revision ID: be4da80c93f1
Revises: 202655005c5c
Create Date: 2025-03-03 18:52:17.356363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be4da80c93f1"
down_revision: Union[str, None] = "202655005c5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("specialists", sa.Column("uuid", sa.UUID(), nullable=False))
    op.create_unique_constraint(None, "specialists", ["uuid"])
    op.add_column("vacancies", sa.Column("uuid", sa.UUID(), nullable=False))
    op.add_column("vacancies", sa.Column("salary", sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, "vacancies", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vacancies", type_="unique")
    op.drop_column("vacancies", "salary")
    op.drop_column("vacancies", "uuid")
    op.drop_constraint(None, "specialists", type_="unique")
    op.drop_column("specialists", "uuid")
    # ### end Alembic commands ###
