"""created_by

Revision ID: c7e8d52dc02f
Revises: 0fc5c5aadbdc
Create Date: 2025-03-09 16:49:00.821018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e8d52dc02f'
down_revision: Union[str, None] = '0fc5c5aadbdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('specialists_created_by_key', 'specialists', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('specialists_created_by_key', 'specialists', ['created_by'])
    # ### end Alembic commands ###
